name: Send Redis Message
description: Push a message to Redis queue
inputs:
  message:
    description: 'The message to send to the Redis queue'
    required: true
  redis_password:
    description: 'Redis password passed in from workflow secrets'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: pip install requests
      shell: bash

    - name: Download script
      run: curl -O https://raw.githubusercontent.com/dmzoneill/dmzoneill/main/redis-notify.py
      shell: bash

    - name: Run redis-notify.py
      run: |
        python redis-notify.py "${{ inputs.message }}"
      shell: bash
      env:
        REDIS_PASSWORD: ${{ inputs.redis_password }}
