name: Send Redis Message
description: Push a message to Redis queue
inputs:
  message:
    description: 'The message to send to the Redis queue'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Redis client
      run: pip install redis
      shell: bash

    - name: Download script
      run: curl -O https://raw.githubusercontent.com/dmzoneill/dmzoneill/refs/heads/main/redis.py
      shell: bash

    - name: Run redis.py
      run: |
        python redis.py "${{ inputs.message }}"
      shell: bash
      env:
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
