name: CICD

on:
  repository_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'
    
permissions: write-all

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: Run linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_MARKDOWN: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-profile:
    runs-on: ubuntu-latest
    name: Update Profile
    needs: run-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update profile
        env:
          ghtoken: ${{ secrets.PUBLISH }}
        run: |-
          python updater.py
          rm super-linter.log

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' #optional defaults to master

  install-action:
    runs-on: ubuntu-latest
    name: Install action
    needs: update-profile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: bash setup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROFILE_HOOK: ${{ secrets.PROFILE_HOOK }}
