name: CICD

on:
  repository_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'
    
permissions: write-all

jobs:
  build:
    name: Update readme
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      env:
         ghtoken: ${{ secrets.PUBLISH }}
      run: python updater.py
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main' #optional defaults to master
