name: CICD_REPOS_SETUP

on:
  push:
  schedule:
    - cron: '0 0 * * *'
    
permissions: write-all

jobs:
  setup-repos:
    runs-on: ubuntu-latest
    name: Setup repos
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: python3 setup.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROFILE_HOOK: ${{ secrets.PROFILE_HOOK }}
          ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
          ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          AI_MODEL: ${{ secrets.AI_MODEL }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          PUBLISH: ${{ secrets.PUBLISH }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          WORDPRESS_APPLICATION: ${{ secrets.WORDPRESS_APPLICATION }}
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}